### ISSUE TITLE
Research best practice for Web App front-end.

### ISSUE THREAD

**Issue by carlin010** [niklasfink/class-survey#6]
The web app front-end is for students taking the survey. This web-app will also include functionality for the admin to create and send surveys to the class.

**Comment by carlin010** [comment]
This link explains how to separate the views based on the device.

http://stackoverflow.com/questions/16297238/angularjs-different-views-based-on-desktop-or-mobile

**Comment by carlin010** [comment]
Arguments against using Ionic as a desktop app.

http://stackoverflow.com/questions/26560204/use-of-ionic-as-desktop-web-application

**Comment by carlin010** [comment]
We need to figure out how we can separate the two builds (desktop, mobile). All of our app logic should be independent from the "front-end" UIs. This should allow us to use the same logic but display the content on the appropriate UI based on the display.
I feel the best solution is have a mobile app only interface and a web browser only interface that works for most/all device sizes.

**Comment by niklasfink** [comment]
I also go in this direction. I share the answer

> [...] share your services and controllers, but use different views for desktop. Ionic is purely focused on mobile.
> http://stackoverflow.com/a/26560362  

<br />As you said, we should have a responsive web browser interfaces which fits all screen sizes and has all functions. Additionally to that we will have the Ionic Hybrid app wich only supports the administration dashboard, as survey-takers won't download an app to participate, but still want to do it on their phones.

|  | Web App | Ionic App |
| --- | --- | --- |
| **Functions** | All | Admin Dashboard |
| **Screensizes** | All | Only on mobile |
| **Database in V1** | Firebase | Firebase |
| **Backend (Angular 2)** | same components | same components |

<br />I made the distinction with V1, because MySQL is also planned.
